apiVersion: v1
kind: Secret
metadata:
  name: tokoxpress-secret
  namespace: tokoxpress
type: Opaque
stringData:
  APP_KEY: "base64:0iEESgWONjzgJYWkDBYWo7UU2qwFWVYZ1zjx1EeS47A="
  DB_USERNAME: "tokouser"
  DB_PASSWORD: "tokopass"
